version: '3'

services:
  mysql57:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "mestre"
    ports:
      - "3307:3306"
    volumes:
      - $PWD/data_56:/var/lib/mysql
      - $PWD/conf:/etc/mysql/mysql.conf.d
    networks:
      - jira-common-network

networks: 
  jira-common-network:
    driver: bridge
