version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "mestre"
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data:/var/lib/mysql
      - $PWD/conf:/etc/mysql/mysql.conf.d
    networks:
      - mysql-common-network

networks: 
  mysql-common-network:
    driver: bridge